### PR TITLE
Update french translation #9

### PR DESCRIPTION
**Pull request by MathDuck**
Add/Update french translation.

### CODE REVIEW

**Comment by TitanNano** [comment]
For #9

**Comment by MathDuck** [comment]
Can't pull the current repo to make the changes...

`error: invalid path 'package/E882D22F!00000000!988382DA4F438C87.TitanNano:Interaction_Make_Not_Selectable.InteractionTuning.xml'`

**Comment by TitanNano** [comment]
@MathDuck that is strange. I'll merge this anyway, and we can update the package before the next release.

**Comment by TitanNano** [comment]
@MathDuck you are running windows I assume? Might be that it doesn't like all the exclamation points and long file names.

**Comment by MathDuck** [comment]
Yes, i use windows and i thought it was related to it. I will try to update it with a Linux VM. Thank you!

**Comment by TitanNano** [comment]
@MathDuck you could also try to use the Windows subsystem for Linux, if you like.

**Pull request merged**
